- alias: Turn on Red Upper Stair Light on Shutdown
  trigger:
    platform: homeassistant
    event_type: shutdown
  action:
    - service: light.turn_on
      data:
        brightness: 255
        rgb_color: [0, 255, 0]
        entity_id:
        - light.bar_table
