- id: appdaemon_heartbeat_checker
  alias: 'Appdaemon Heartbeat Checker'
  initial_state: 'on'
  condition:
    condition: template
    value_template: >
      {%- if states.sensor.appdaemon_heartbeat.last_changed -%}
        {{ (as_timestamp(now()) - as_timestamp(states.sensor.appdaemon_heartbeat.last_changed)) > 300 }}
      {%- else -%}
        true
      {%- endif -%}
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
    - service: notify.kevin
      data:
        title: 'Alarm'
        message: "Appdaemon scheint nicht mehr zu funktionieren"
#################################################################
## Turn on/off Alexa Notifications on Sleepmode
#################################################################
- id: turn_off_alexa_notifications_when_sleeping
  alias: 'Alexa Ansagen aus wenn wir schlafen'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sleepmode
      from: "off"
      to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.notifier_alexa
- id: turn_on_alexa_notifications_when_sleeping
  alias: 'Alexa Ansagen an wenn wir aufstehen'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sleepmode
      from: "on"
      to: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.notifier_alexa


      