- id: appdaemon_heartbeat_checker
  alias: 'Appdaemon Heartbeat Checker'
  initial_state: 'on'
  condition:
    condition: template
    value_template: >
      {%- if states.sensor.appdaemon_heartbeat.last_changed -%}
        {{ (as_timestamp(now()) - as_timestamp(states.sensor.appdaemon_heartbeat.last_changed)) > 300 }}
      {%- else -%}
        true
      {%- endif -%}
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
    - service: notify.kevin
      data:
        title: 'Alarm'
        message: "Appdaemon scheint nicht mehr zu funktionieren"
#################################################################
## New Home Assistant Version
#################################################################
- id: new_homeassistant_version
  alias: 'Notify of new Homeassistant Version'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_assistant_latest_docker
  action:
    - service: notify.kevin
      data_template:
        message: "Neue Homeassistant Version verfügbar: {{states.sensor.home_assistant_latest_docker.state}}"
#################################################################
## New Unifi Controller Version
#################################################################
- id: new_unifi_controller_version
  alias: 'Notify of new Unifi Controller Version'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.unifi_controller_latest_docker
  action:
    - service: notify.kevin
      data_template:
        message: "Neue Unifi Controller Version verfügbar: {{states.sensor.unifi_controller_latest_docker.state}}"