- id: appdaemon_heartbeat_checker
  alias: 'Appdaemon Heartbeat Checker'
  initial_state: 'on'
  condition:
    condition: template
    value_template: >
      {%- if states.sensor.appdaemon_heartbeat.last_changed -%}
        {{ (as_timestamp(now()) - as_timestamp(states.sensor.appdaemon_heartbeat.last_changed)) > 300 }}
      {%- else -%}
        true
      {%- endif -%}
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
    - service: notify.kevin
      data:
        title: 'Alarm'
        message: "Appdaemon scheint nicht mehr zu funktionieren"
#################################################################
## New Home Assistant Version
#################################################################
- id: new_homeassistant_version
  alias: 'Notify of new Homeassistant Version'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.home_assistant_latest_docker
  action:
    - service: notify.kevin
      data_template:
        message: "Neue Homeassistant Version verfügbar: {{states.sensor.home_assistant_latest_docker.state}}"
  condition:
    condition: template
    value_template: >
      {{ trigger.to_state.state not in [trigger.from_state.state, 'unavailable'] }}
#################################################################
## New Unifi Controller Version
#################################################################
- id: new_unifi_controller_version
  alias: 'Notify of new Unifi Controller Version'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.unifi_controller_latest_docker
  action:
    - service: notify.kevin
      data_template:
        message: "Neue Unifi Controller Version verfügbar: {{states.sensor.unifi_controller_latest_docker.state}}"
  condition:
    condition: template
    value_template: >
      {{ trigger.to_state.state not in [trigger.from_state.state, 'unavailable'] }}
#################################################################
## Turn on/off Alexa Notifications on Sleepmode
#################################################################
- id: turn_off_alexa_notifications_when_sleeping
  alias: 'Alexa Ansagen aus wenn wir schlafen'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sleepmode
      from: "off"
      to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.notifier_alexa
- id: turn_on_alexa_notifications_when_sleeping
  alias: 'Alexa Ansagen an wenn wir aufstehen'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.sleepmode
      from: "on"
      to: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.notifier_alexa


      