- alias: Notify for new devices
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.group_notifications
      data:
        message: >
          Unbekanntes Gerät entdeckt:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
        title: Unbekanntes Gerät entdeckt

- alias: Turn on Red Upper Stair Light on Shutdown
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: light.turn_on
      data:
        brightness: 255
        rgb_color: [0, 255, 0]
        entity_id:
        - light.bar_table
