#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant

# CustomUI
customizer:
  custom_ui: local


frontend:
  themes: !include themes.yaml
updater:
  reporting: no
  include_used_components: true
sun:
map:
config:

logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

logbook:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret homeassistant_url
  ip_ban_enabled: True
  login_attempts_threshold: 3
  use_x_forwarded_for: True
  trusted_proxies:
    - !secret proxy_ip

history:

#################################################################
## Components
#################################################################

emulated_hue:
  host_ip: !secret homeassistant_host_ip
  type: alexa
  expose_by_default: false

mqtt:
  broker: !secret mqtt_host 
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_user
  password: !secret mqtt_pass
  keepalive: 60

recorder:
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.snowie_map

device_tracker:
  - platform: fritz
    track_new_devices: yes
  - platform: gpslogger

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac:
      key: !secret xiaomi_aqara_key

media_player:
  - platform: denonavr
    host: !secret denon_ip
  - platform: kodi
    host: !secret kodi_ip
    port: 8080
  - platform: emby
    host: !secret emby_ip
    api_key: !secret emby_api_key
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: "amazon.de"

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_key

influxdb:
  database: !secret influxdb_db_name
  username: !secret influxdb_user
  password: !secret influxdb_password

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_allowed_chat_id_group_notifications
      - !secret telegram_allowed_chat_id_user_one
      - !secret telegram_allowed_chat_id_user_two  

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

custom_updater:
  track:
    - components
    - cards
  card_urls:
    - https://raw.githubusercontent.com/custom-cards/information/master/repos.json
  component_urls:
    - https://raw.githubusercontent.com/custom-components/information/master/repos.json

panel_iframe:
  floorplan_upper:
    title: Oben
    url: /lovelace/view_floorplan_upper
    icon: mdi:home-assistant
  floorplan_lower:
    title: Unten
    url: /lovelace/view_floorplan_lower
    icon: mdi:home-assistant
#  pihole:
#    title: 'Pi-Hole'
#    url: !secret pihole_ip
#    icon: mdi:block-helper
#################################################################
## Includes
#################################################################

alexa: !include alexa.yaml
switch: !include switch.yaml
sensor: !include sensor.yaml
group: !include group.yaml
automation: !include automation.yaml
script: !include scripts.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
zone: !include zone.yaml
proximity: !include proximity.yaml
camera: !include camera.yaml
image_processing: !include image_processing.yaml
android_ip_webcam: !include android_ip_webcam.yaml
history_graph: !include history_graph.yaml
input_select: !include input_select.yaml
input_datetime: !include input_datetime.yaml
binary_sensor: !include binary_sensor.yaml
weather: !include weather.yaml
climate: !include climate.yaml
counter: !include counter.yaml
scene: !include scenes.yaml