- platform: mqtt_json
  name: bar_table
  state_topic: "RGBW/00D2EE20/json/state"
  command_topic: "RGBW/00D2EE20/json/set"
  brightness: true
  rgb: true
  white_value: true

- platform: yeelight
  devices:
    !secret bedroom_yeelight_ip:
      name: Bedroom_Yeelight
      transition: 1000
    !secret stairs_lower_yeelight_ip:
      name: stairs_lower_yeelight
      transition: 1000
    !secret reading_lamp_yeelight_ip:
      name: reading_lamp_yeelight
      transition: 1000
    !secret lobby_yeelight_ip:
      name: lobby_yeelight

- platform: xiaomi_miio
  name: Treppe Oben
  host: !secret xiaomi_treppe_oben_ip
  token: !secret xiaomi_treppe_oben_token
  model: philips.light.bulb

- platform: mqtt
  name: bar_table
  state_topic: "stat/bar_light/RESULT"
  command_topic: "cmnd/bar_light/POWER"
  state_value_template: "{{ value_json.POWER }}"
  brightness_state_topic: "stat/bar_light/RESULT"
  brightness_command_topic: "cmnd/bar_light/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  white_value_state_topic: "stat/bar_light/RESULT"
  white_value_command_topic: "cmnd/bar_light/Channel4"
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  rgb_command_topic: "cmnd/bar_light/Color"
  rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
  rgb_state_topic: "stat/bar_light/RESULT"
  rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"
  effect_state_topic: "stat/bar_light/RESULT"
  effect_command_topic: "cmnd/bar_light/Scheme"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  retain: false
  qos: 2
  payload_on: "ON"
  payload_off: "OFF"