#################################################################
## Darksky
#################################################################
- platform: darksky
  api_key: !secret darsky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - temperature_max
    - temperature_min
#################################################################
## Room Presence
#################################################################
- platform: mqtt
  name: room_user_one
  state_topic: !secret room_user_one_state_topic # "crows/location/RogueCrow"
  value_template: '{{ value_json.location }}'
- platform: mqtt
  name: room_user_two
  state_topic: !secret room_user_two_state_topic # "crows/location/RogueCrow"
  value_template: '{{ value_json.location }}'
#################################################################
## Sonoff
#################################################################
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  name: 'Small Lamp Temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  name: 'Small Lamp Humidity'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  name: 'Large Lamp Temperature'
  unit_of_measurement: '°C'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  name: 'Large Lamp Humidity'
  unit_of_measurement: '%'
#################################################################
## Travel Times
#################################################################
- platform: template
  sensors:
    travel_time_work_from_home:
      friendly_name: !secret sensor_friendy_name_travel_time_work_from_home
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_work_from_home') | int}}"
    travel_time_home_from_work:
      friendly_name: !secret sensor_friendy_name_travel_time_home_from_work
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_home_from_work') | int}}"
    travel_time_elmo_from_home:
      friendly_name: !secret sensor_friendy_name_travel_time_elmo_from_home
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_elmo_from_home') | int}}"

      