#################################################################
## Weather
#################################################################
- platform: darksky
  api_key: !secret darsky_api_key
  language: de
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_intensity_max 
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - temperature_high
    - temperature_low
- platform: yr
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
- platform: dwd_weather_warnings
  region_name: !secret dwd_weather_warnings_region
#################################################################
## Sun
#################################################################
- platform: template
  sensors:
    sunset_time:
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}"
      friendly_name: Sonnenuntergang
      entity_id:
       - sun.sun
    sunrise_time:
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}"
      friendly_name: Sonnenaufgang
      entity_id:
       - sun.sun
    solar_angle:
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      friendly_name: Solar Angle
      unit_of_measurement: degrees
      entity_id:
       - sun.sun
#################################################################
## Uptime
#################################################################
- platform: uptime
  name: Uptime
  unit_of_measurement: minutes
#################################################################
## SQL
#################################################################
- platform: sql
  db_url: !secret db_url
  queries:
    - name: DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="hass_db" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
