#################################################################
## Darksky
#################################################################
- platform: darksky
  api_key: !secret darsky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - temperature_max
    - temperature_min
#################################################################
## Room Presence
#################################################################
- platform: mqtt
  name: mqtt_room_user_one
  state_topic: !secret room_user_one_state_topic
  value_template: '{{ value_json.location }}'
- platform: mqtt
  name: mqtt_room_user_two
  state_topic: !secret room_user_two_state_topic
  value_template: '{{ value_json.location }}'
#Rename sensors in frontend
- platform: template
  sensors:
    room_user_one:
      friendly_name: !secret user_one_name
      value_template: >-
        {% if is_state('sensor.mqtt_room_user_one', 'livingroom') %}
          Wohnzimmer
        {% elif is_state('sensor.mqtt_room_user_one', 'kitchen') %}
          K체che
        {% elif is_state('sensor.mqtt_room_user_one', 'studyroom') %}
          Arbeitszimmer
        {% elif is_state('sensor.mqtt_room_user_one', 'bedroom') %}
          Schlafzimmer
        {% elif is_state('sensor.mqtt_room_user_one', 'lower_bathroom') %}
          Bad unten
        {% elif is_state('sensor.mqtt_room_user_one', 'upper_bathroom') %}
          Bad oben
        {% elif is_state('sensor.mqtt_room_user_one', 'upper_balcony') %}
          Balkon Oben
        {% else %}
          Unbekannt
        {% endif %}
    room_user_two:
      friendly_name: !secret user_two_name
      value_template: >-
        {% if is_state('sensor.mqtt_room_user_two', 'livingroom') %}
          Wohnzimmer
        {% elif is_state('sensor.mqtt_room_user_two', 'kitchen') %}
          K체che
        {% elif is_state('sensor.mqtt_room_user_two', 'studyroom') %}
          Arbeitszimmer
        {% elif is_state('sensor.mqtt_room_user_two', 'bedroom') %}
          Schlafzimmer
        {% elif is_state('sensor.mqtt_room_user_two', 'lower_bathroom') %}
          Bad unten
        {% elif is_state('sensor.mqtt_room_user_two', 'upper_bathroom') %}
          Bad oben
        {% elif is_state('sensor.mqtt_room_user_one', 'upper_balcony') %}
          Balkon Oben
        {% else %}
          Unbekannt
        {% endif %}
#################################################################
## Sonoff
#################################################################
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  name: 'Small Lamp Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  name: 'Small Lamp Humidity'
  unit_of_measurement: '%'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  name: 'Large Lamp Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "tele/sonoff_small_lamp/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  name: 'Large Lamp Humidity'
  unit_of_measurement: '%'
#################################################################
## Travel Times
#################################################################
#Set by Appdaemon
- platform: template
  sensors:
    travel_time_work_from_home:
      friendly_name: !secret sensor_friendy_name_travel_time_work_from_home
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_work_from_home') | int}}"
    travel_time_home_from_work:
      friendly_name: !secret sensor_friendy_name_travel_time_home_from_work
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_home_from_work') | int}}"
    travel_time_elmo_from_home:
      friendly_name: !secret sensor_friendy_name_travel_time_elmo_from_home
      unit_of_measurement: "min"
      value_template: "{{ states('input_number.travel_time_elmo_from_home') | int}}"

#Google
- platform: google_travel_time
  name: Zu Hause -> SVA
  api_key: !secret google_maps_api_token
  origin: zone.home
  destination: zone.work

#Waze
- platform: waze_travel_time
  origin: !secret waze_home
  destination: !secret waze_work
  region: EU
#################################################################
## Next Appointment
#################################################################
- platform: template
  sensors:
    cal_next_appointment_title:
      friendly_name: Termin
      value_template: "{{ states.calendar.keifingergooglemailcom.attributes.message }}"
    cal_next_appointment_location:
      friendly_name: Ort
      value_template: "{{ states.calendar.keifingergooglemailcom.attributes.location }}"
    cal_next_appointment_start_time:
      friendly_name: Um
      value_template: "{{ states.calendar.keifingergooglemailcom.attributes.start_time }}"
#################################################################
## Sun
#################################################################
- platform: template
  sensors:
    sunset_time:
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}"
      friendly_name: Sonnenuntergang
    sunrise_time:
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}"
      friendly_name: Sonnenaufgang
    solar_angle:
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      friendly_name: Solar Angle
      unit_of_measurement: degrees