- platform: mqtt
  name: "Snowboard"
  state_topic: "stat/sonoff_snowboard/POWER"
  command_topic: "cmnd/sonoff_snowboard/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 2
  retain: false
- platform: mqtt
  name: "Large Lamp"
  state_topic: "stat/sonoff_large_lamp/POWER"
  command_topic: "cmnd/sonoff_large_lamp/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 2
  retain: false
- platform: mqtt
  name: "Small Lamp"
  state_topic: "stat/sonoff_small_lamp/POWER"
  command_topic: "cmnd/sonoff_small_lamp/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 2
  retain: false
- platform: mqtt
  name: "Ventilator"
  state_topic: "stat/sonoff_ventilator/POWER"
  command_topic: "cmnd/sonoff_ventilator/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 2
  retain: false

