---
sensor:
  - platform: avanza_stock
    stock: 732452
    name: avanza_bmw
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
input_text:
  avanza_bmw_min:
    icon: mdi:arrow-collapse-down
    name: Min Alert
  avanza_bmw_max:
    icon: mdi:arrow-collapse-up
    name: Max Alert
automation:
  - id: avanza_bmw
    alias: Avanza bmw
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.avanza_bmw') | float > states('input_text.avanza_bmw_max') |float
          and states('input_text.avanza_bmw_max') not in ['unknown', ''] }}
      - platform: template
        value_template: >
          {{ states('sensor.avanza_bmw') | float < states('input_text.avanza_bmw_min') | float
          and states('input_text.avanza_bmw_min') not in ['unknown', ''] }}
    action:
      - service: notify.kevin
        data_template:
          message: >
            {% if states('sensor.avanza_bmw') | float > states('input_text.avanza_bmw_max') | float 
            and states('input_text.avanza_bmw_max') not in ['unknown', ''] %}
            "Stock alert: {{ state_attr('sensor.avanza_bmw','name') }}:
            {{ states('sensor.avanza_bmw') }} {{ state_attr('sensor.avanza_bmw','currency') }}.
            Over threshold of {{ states('input_text.avanza_bmw_max') }}"
            {% else %}
            "Stock alert: {{ state_attr('sensor.avanza_bmw','name') }}:
            {{ states('sensor.avanza_bmw') }} {{ state_attr('sensor.avanza_bmw','currency') }}.
            Under threshold of {{ states('input_text.avanza_bmw_min') }}"
            {% endif %}
