---
automation:
  - id: alert_when_ariela_dell_tablet_battery_lt_15
    alias: 'Alarm wenn Ariela Dell Tablet Batterie < 15%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.venue_8_7840_battery_sensor
        below: 15
        for: "00:05:00"
    action:
      - service: notify.group_notifications
        data:
          message: "Dell Tablet Batterie < 15%"