---
automation:
  - id: alert_when_breaking_changes
    alias: 'Alarm bei Breaking Changes'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.potential_breaking_changes
        above: 0
    action:
      - service: notify.kevin
        data_template:
          message: >
            Potentielle Breaking Changes festgestellt in Version
            {{ states.sensor.potential_breaking_changes.attributes.versions[0] }}
              {% for key, value in states.sensor.potential_breaking_changes.attributes.items() %}
              {% if key not in ('versions', 'friendly_name', 'icon')%}
                Component: {{ value['component'] }}
                Description: {{ value['description'] }}
                PR: {{ value['prlink'] }}
                Doc: {{ value['doclink'] }}
              {% endif %}
            {% endfor %}
