sensor:
  - platform: alpha_vantage
    api_key: !secret alpha_vantage_api_key
    symbols:
      - symbol: MSFT
        name: Microsoft
      - symbol: IBM
        name: IBM
    foreign_exchange:
      - name: Monero
        from: XMR
        to: EUR
  - platform: coinmarketcap
    currency_id: 328
  - platform: avanza_stock
    stock: 4175
    name: avanza_ibm
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - description
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
  - platform: avanza_stock
    stock: 3873
    name: avanza_microsoft
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - description
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
  - platform: rest
    resource: !secret xmr_hashrate_url
    name: Monero Hash Rate
    value_template: "{{ value_json.hash }}"
    unit_of_measurement: H/s
    json_attributes:
      - totalHashes
      - validShares
      - amtPaid
      - amtDue
      - txnCount
  - platform: statistics
    entity_id: sensor.monero_hash_rate
    name: statistics_monero_hash_rate
    max_age:
      hours: 24
  - platform: template
    sensors:
      monero_amount_earned:
        friendly_name: "Monero Amount Earned"
        value_template: "{{ state_attr('sensor.monero_hash_rate', 'amtDue') / 1000000000000 + state_attr('sensor.monero_hash_rate', 'amtPaid') / 1000000000000 }}"
        unit_of_measurement: "XMR"
      monero_total_hashes:
        friendly_name: "Monero Total Shares"
        value_template: "{{ state_attr('sensor.monero_hash_rate', 'totalHashes') }}"
        unit_of_measurement: "Hashes"
      monero_valid_shares:
        friendly_name: "Monero Valid Shares"
        value_template: "{{ state_attr('sensor.monero_hash_rate', 'validShares') }}"
        unit_of_measurement: "Shares"
      monero_hash_share_ratio:
        friendly_name: "Monero Hash to Share Ratio"
        value_template: "{{ state_attr('sensor.monero_hash_rate', 'totalHashes') / state_attr('sensor.monero_hash_rate', 'validShares') }}"
        unit_of_measurement: "Hash/Share"
      monero_average_hash_rate_24_hours:
        friendly_name: "Monero Average Hash Rate 24 Hours"
        value_template: "{{ state_attr('sensor.statistics_monero_hash_rate', 'mean') }}"
        unit_of_measurement: "Hashes"