sensor:
  - platform: alpha_vantage
    api_key: !secret alpha_vantage_api_key
    symbols:
      - symbol: MSFT
        name: Microsoft
      - symbol: IBM
        name: IBM
    foreign_exchange:
      - name: Monero
        from: XMR
        to: EUR
  - platform: coinmarketcap
    currency_id: 328
  - platform: avanza_stock
    stock: 4175
    name: avanza_ibm
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - description
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
  - platform: avanza_stock
    stock: 3873
    name: avanza_microsoft
    monitored_conditions:
      - change
      - changePercent
      - country
      - currency
      - description
      - directYield
      - dividends
      - flagCode
      - hasInvestmentFees
      - highestPrice
      - id
      - isin
      - lastPrice
      - lastPriceUpdated
      - loanFactor
      - lowestPrice
      - marketCapital
      - marketList
      - marketMakerExpected
      - marketPlace
      - marketTrades
      - morningStarFactSheetUrl
      - name
      - numberOfOwners
      - orderDepthReceivedTime
      - priceAtStartOfYear
      - priceEarningsRatio
      - priceFiveYearsAgo
      - priceOneMonthAgo
      - priceOneWeekAgo
      - priceOneYearAgo
      - priceSixMonthsAgo
      - priceThreeMonthsAgo
      - priceThreeYearsAgo
      - pushPermitted
      - quoteUpdated
      - sector
      - shortSellable
      - superLoan
      - tickerSymbol
      - totalNumberOfShares
      - totalValueTraded
      - totalVolumeTraded
      - tradable
      - volatility
  - platform: rest
    resource: !secret xmr_hashrate_url
    name: Monero Hash Rate
    value_template: "{{ value_json.hash }}"
    unit_of_measurement: H/s
    json_attributes:
      - totalHashes
      - validShares
      - amtPaid
      - amtDue
      - txnCount