sensor:
  - platform: glances
    host: !secret pihole_ip
    name: glances_pihole
    version: 3
    username: !secret glances_pihole_username
    password: !secret glances_pihole_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: glances
    host: !secret zigbee2mqtt_ip
    name: glances_zigbee2mqtt
    version: 3
    username: !secret glances_zigbee2mqtt_username
    password: !secret glances_zigbee2mqtt_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'

automation:
  - id: alert_when_glances_pihole_disk_used_gt_80
    alias: 'Alarm wenn Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_pihole_disk_used_2
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "PiHole Disk Usage über 80%"

  - id: alert_when_glances_zigbee2mqtt_disk_used_gt_80
    alias: 'Alarm wenn Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_zigbee2mqtt_disk_used_2
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "ZIgbee2MQTT Disk Usage über 80%"