sensor:
- platform: here_travel_time
  name: travel_time_work_from_home_here
  origin: zone.home
  destination: zone.work
  app_id: !secret here_app_id
  app_code: !secret here_app_code
#Home from Work
- platform: here_travel_time
  name: travel_time_home_from_work_here
  origin: zone.work
  destination: zone.home
  app_id: !secret here_app_id
  app_code: !secret here_app_code
#Elmo from Home
- platform: here_travel_time
  name: travel_time_elmo_from_home_here
  origin: zone.home
  destination: zone.elmo
  app_id: !secret here_app_id
  app_code: !secret here_app_code