sensor:
# Work from Home
- platform: here_travel_time
  name: travel_time_work_from_home_here
  origin_entity_id: zone.home
  destination_entity_id: zone.work
  app_id: !secret here_app_id
  app_code: !secret here_app_code
# Home from Work
- platform: here_travel_time
  name: travel_time_home_from_work_here
  origin_entity_id: zone.work
  destination_entity_id: zone.home
  app_id: !secret here_app_id
  app_code: !secret here_app_code
# Elmo from Home
- platform: here_travel_time
  name: travel_time_elmo_from_home_here
  origin_entity_id: zone.home
  destination_entity_id: zone.elmo
  app_id: !secret here_app_id
  app_code: !secret here_app_code
# Next Appointment
- platform: here_travel_time
  name: travel_time_next_appointment_location_here
  origin_entity_id: !secret device_user_one
  destination_entity_id: sensor.cal_next_appointment_location_google_prepared
  app_id: !secret here_app_id
  app_code: !secret here_app_code
- platform: here_travel_time
  name: travel_time_next_appointment_location_here_user_two
  origin_entity_id: !secret device_user_two
  destination_entity_id: sensor.cal_next_appointment_location_google_prepared_user_two
  app_id: !secret here_app_id
  app_code: !secret here_app_code

homeassistant:
  customize:
    sensor.travel_time_work_from_home_here:
      friendly_name: "Zu Hause -> SVA"
    sensor.travel_time_home_from_work_here:
      friendly_name: "SVA -> Zu Hause"
    sensor.travel_time_elmo_from_home_here:
      friendly_name: "Zu Hause -> Elmo"