---
sensor:
  - platform: pi_hole
    host: !secret pihole_ip
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
  - platform: pi_hole
    host: !secret zigbee2mqtt_ip
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today

switch:
  - platform: command_line
    switches:
      pihole_switch:
        command_on: !secret pihole_switch_on #"curl -X GET 'http://192.168.10.11/admin/api.php?enable&auth=xxx'"
        command_off: !secret pihole_switch_off #"curl -X GET 'http://192.168.10.11/admin/api.php?disable=3600&auth=xxx'"
        command_state: !secret pihole_switch_state # "curl -X GET 'http://192.168.10.11/admin/api.php?status'| grep enabled"
        value_template: "{{ value_json.status == 'enabled' }}"
