sensor:
  - platform: pi_hole
    host: !secret pihole_ip
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
  - platform: pi_hole
    host: !secret zigbee2mqtt_ip
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today