---
sensor:
  - platform: mqtt
    state_topic: "pibakery-eifinger/ip"
    qos: 1
    name: "Publish IP On Boot"

automation:
  - id: publish_ip_on_boot_listener
    alias: 'Notify when Publish IP on Boot is used'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.publish_ip_on_boot
    action:
      - service: notify.kevin
        data:
          message: "Neue IP über Publish IP On Boot: {{states.sensor.publish_ip_on_boot.state}}"
