---
sensor:
  - platform: rmvtransport
    next_departure:
      - station: 3025386
        name: Ruthof
        time_offset: 5
        products:
          - 'RB'
          - 'RE'
          - 'Bus'
          - 'S'
      - station: 3025386
        name: Nach Brückenkopf
        destinations: ['Wiesbaden-Mainz-Kastel Brückenkopf']
