sensor:
  - platform: glances
    host: !secret pihole_ip
    name: glances_pihole
    version: 3
    username: !secret glances_pihole_username
    password: !secret glances_pihole_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: glances
    host: !secret zigbee2mqtt_ip
    name: glances_zigbee2mqtt
    version: 3
    username: !secret glances_zigbee2mqtt_username
    password: !secret glances_zigbee2mqtt_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: glances
    host: !secret glances_host
    name: glances_host
    version: 3
    username: !secret glances_host_username
    password: !secret glances_host_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: glances
    host: !secret glances_odroid
    name: glances_odroid
    version: 3
    username: !secret glances_odroid_username
    password: !secret glances_odroid_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: glances
    host: !secret glances_wackernheim_pi
    port: !secret glances_wackernheim_pi_port
    name: glances_wackernheim_pi
    version: 3
    username: !secret glances_wackernheim_pi_username
    password: !secret glances_wackernheim_pi_password
    resources:
      - 'disk_use'
      - 'disk_use_percent'
      - 'disk_free'
      - 'cpu_temp'
      - 'processor_load'
      - 'memory_use'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: !secret host_path_disk1
      - type: disk_use
        arg: !secret host_path_disk1
      - type: disk_free
        arg: !secret host_path_disk1
      - type: disk_use_percent
        arg: !secret host_path_disk2
      - type: disk_use
        arg: !secret host_path_disk2
      - type: disk_free
        arg: !secret host_path_disk2
      - type: disk_use_percent
        arg: !secret host_path_disk3
      - type: disk_use
        arg: !secret host_path_disk3
      - type: disk_free
        arg: !secret host_path_disk3
      - type: disk_use_percent
        arg: !secret host_path_disk4
      - type: disk_use
        arg: !secret host_path_disk4
      - type: disk_free
        arg: !secret host_path_disk4

automation:
  - id: alert_when_glances_pihole_disk_used_gt_80
    alias: 'Alarm wenn PiHole Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_pihole_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "PiHole Disk Usage über 80%"

  - id: alert_when_glances_zigbee2mqtt_disk_used_gt_80
    alias: 'Alarm wenn Zigbee2MQTT Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_zigbee2mqtt_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Zigbee2MQTT Disk Usage über 80%"

  - id: alert_when_glances_host_disk_used_gt_80
    alias: 'Alarm wenn Host Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_host_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk Usage über 80%"

  - id: alert_when_glances_odroid_disk_used_gt_80
    alias: 'Alarm wenn Odroid Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_odroid_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Odroid Disk Usage über 80%"

  - id: alert_when_glances_wackernheim_pi_disk_used_gt_80
    alias: 'Alarm wenn Wackernheim Pi Disk Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.glances_wackernheim_pi_disk_used
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Wackernheim Pi Disk Usage über 80%"

  - id: alert_when_host_disk1_used_gt_80
    alias: 'Alarm wenn Host Disk1 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk1_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk1 Usage über 80%"

  - id: alert_when_host_disk2_used_gt_80
    alias: 'Alarm wenn Host Disk2 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk2_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk2 Usage über 80%"

  - id: alert_when_host_disk3_used_gt_80
    alias: 'Alarm wenn Host Disk3 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk3_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk3 Usage über 80%"

  - id: alert_when_host_disk4_used_gt_80
    alias: 'Alarm wenn Host Disk4 Used > 80%'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: !secret host_disk4_usage_sensor
        above: 80
    action:
      - service: notify.kevin
        data:
          message: "Host Disk4 Usage über 80%"

  - id: alert_when_check_seafile_failed
    alias: 'Alarm wenn Seafile fsck fehlgeschlagen'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.seafile_fsck
        from: "on"
        to: "off"
    action:
      - service: notify.kevin
        data:
          message: "Seafile fsck ist fehlgeschlagen"
